### ISSUE TITLE
3.0: Packets don't seem to be wrapped

### ISSUE THREAD

**Issue by SamB440** [ThomasOM/Pledge#14]
I'm using createFramePinger. The transactions don't seem to wrap the packets of the server tick:
![image](https://github.com/ThomasOM/Pledge/assets/11319274/00265187-9734-4fca-ae45-35cb68082fc3)
Pipeline is:
`[pledge_queue_handler, FlushConsolidationHandler#0, timeout, decrypt, splitter, decompress, pe-decoder-pharus, decoder, encrypt, prepender, compress, pe-encoder-pharus, encoder, unbundler, bundler, FlowControlHandler#0, pledge_packet_listener, packet_handler, pledge_queue_primer, DefaultChannelPipeline$TailContext#0]`

**Comment by ThomasOM** [comment]
Investigating

**Comment by ThomasOM** [comment]
Seems to be caused by the new pipeline now after 1.20.2

**Comment by ThomasOM** [comment]
> Seems to be caused by the new pipeline now after 1.20.2

I was wrong, very stupid mistake... https://github.com/ThomasOM/Pledge/commit/b20ceff0e719a29ceb839863dde7e9263966d94d

**Comment by ThomasOM** [comment]
Feel free to reopen if issue still persists

**Comment by SamB440** [comment]
I now seem to get a bunch of DecoderException's when using the frame pinger, but the normal clientpinger works fine
```java
        this.pledge = Pledge.getOrCreate(this); // Create or get when already registered to another plugin
        framePinger = pledge.createFramePinger(1, 200);
        this.getServer().getPluginManager().registerEvents(this, this);
        Bukkit.getScheduler().scheduleSyncRepeatingTask(this, () -> {
            for (Player onlinePlayer : Bukkit.getOnlinePlayers()) {
                framePinger.getOrCreate(onlinePlayer);
            }
        }, 0L, 1L);
```

**Comment by SamB440** [comment]
I think it must be something to do with the additional pipeline handlers, but I don't know enough about these for what the issue could be

**Comment by ThomasOM** [comment]
I'm able to reproduce this, seems to be a different issue

**Comment by SamB440** [comment]
@ThomasOM 
Reverting the position of the handlers to 2.0 behaviour worked for me: https://github.com/EmpireWar/Pledge/commit/b4a6cf255071d63e97d66e3a8d95757087fc6fcc

```java
channel.pipeline()
            .addAfter("prepender", "pledge_queue_handler", queueHandler)
            .addAfter("encoder", "pledge_queue_primer", queuePrimer);
```

**Comment by SamB440** [comment]
Oh but that breaks the packet type checks. Still looking into this though. On Velocity the first transaction also breaks as it's sent just before join game which the proxy doesn't seem to like.

**Comment by SamB440** [comment]
Actually just moving the queue handler is sufficient. The primer needs to be last otherwise the filter doesn't work. It also needs to check if there is a login packet to prevent a ping being sent before the join game packet which breaks on proxies.

**Comment by ThomasOM** [comment]
@SamB440
Thanks for the investigation, I'll make sure to test moving the queue handler after the prepender instead

**Comment by SamB440** [comment]
I believe `MessageQueueHandler` also needs its QueueMode set to `ADD_LAST` initially as it seems it gets stuck on `LAST` during login otherwise, skipping some packets that should be wrapped

**Comment by ThomasOM** [comment]
See: https://github.com/ThomasOM/Pledge/commit/78a3648694ab4e23da5fe504a860bfe42f802f50.
I tested this on 1.20.4 and it seems to work just fine 👍

Also made sure to use `ADD_LAST` for `MessageQueueHandler` the moment the login packet is received so you don't miss out on any packets
