### ISSUE TITLE
Player can do some * in console

### ISSUE THREAD

**Issue by murqe** [ThomasOM/Pledge#19]
The idea was that I wanted to kick a player when the "onPongReceiveInvalid" event triggered, however this has caused some problems

Pledge listener code:
![image](https://github.com/user-attachments/assets/28b9a18b-cc09-47af-a93f-a3401aad3a19)

So I have this peace of code in a hacked client which I'm using:
![image](https://github.com/user-attachments/assets/6c217900-2fbb-4bb3-ac6c-224eb1c9cf28)
When I'm connecting to the server with it:
![image](https://github.com/user-attachments/assets/4d9e0909-94f7-47fe-a926-2dc22e746260)
however, if I was already connected to the server and "playing" for at least one second (or maybe less), it would be fine

**Comment by ThomasOM** [comment]
Thanks, found a fix for this and will close the issue once deployed

**Comment by ThomasOM** [comment]
Fixed in https://github.com/ThomasOM/Pledge/commit/8a0bd9e34dd7669d805f603ed439c6dd1752b8b2
