### ISSUE TITLE
Pledge interacts badly with PacketEvents

### ISSUE THREAD

**Issue by SamB440** [ThomasOM/Pledge#8]
Hi, haven't used Pledge for a while but have started to again.

Pledge works fine by itself, and will still work when using PacketEvents alongside it, however using PacketEvent's write or send packet methods does not result in the packet being sent to the player. It does call PacketSendEvent (which is called when the packet is written, to my knowledge), but the player never actually receives the packet.

I don't think this is related to bundles. I tried forcefully disabling the bundle support but the same issue happened. This happens with any plugin on the server that uses PacketEvents, not just the one utilising Pledge.

This is the result of PE's `ChannelHelper#pipelineHandlerNamesAsString` (might be helpful?):
![image](https://github.com/ThomasOM/Pledge/assets/11319274/6a38b041-bfa7-456e-b566-0d3a4bdd19b7)

To easily reproduce, just setup a project with PacketEvents and Pledge and try sending a knockback packet to the player using PacketEvents.

Using Pledge 2.4, latest PacketEvents 2.0 and the server is Paper 1.19.4.

**Comment by ThomasOM** [comment]
Thanks, aware of this and a fix is pending. Need to inject later into the pipeline to be behind PacketEvents handlers.

**Comment by ThomasOM** [comment]
Version 2.5 should fix this, I tested it using a packetevents debug plugin. Verified it not working before and working after my latest updates. Please let me know if your issue is resolved.

**Comment by SamB440** [comment]
Hi, I can confirm the issue is fixed.

Thanks!
